// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShowKeybindings
{
    internal sealed partial class Vsix
    {
        public const string Id = "ShowKeybindings.f73046e8-4338-4054-9160-0c3aa88fd34c";
        public const string Name = "My Keyboard Shortcuts";
        public const string Description = @"Exports all your keybindings to a document that's easy to read for you reference. Supports both text and HTML formats.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
