// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShowKeybindings
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ShowKeybindingsString = "f756c255-fb41-4603-832b-7f781a6a71c6";
        public static Guid ShowKeybindings = new Guid(ShowKeybindingsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Group = 0x1000;
        public const int ListAll = 0x0100;
    }
}